version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/src
    depends_on:
      - database
    tty: true
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    image: postgres:13.2
    ports:
      - "5005:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: tweets

