version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/src
    tty: true
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
